title: "Imputación de Datos"
author: "Juan Camilo Conrado Pacheco"
language: es
logo: null

execute:
  execute_notebooks: "force"
  timeout: -1

html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
