title: "Taller de Imputación de Datos"
author: "Juan Camilo Conrado Pacheco"
logo: logo.png   

repository:
  url: https://github.com/JuanConrado/taller-imputacion
  branch: main
  path_to_book: docs

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
